plugins {
    id 'com.android.application'
}

android {
    namespace 'br.senai.gostop'
    compileSdk 35

    defaultConfig {
        applicationId 'br.senai.gostop'
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.google.ai.edge.litert:litert:1.4.2'
}
